//login
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

//logout
export const LOGOUT = "LOGOUT";

//getting infos
export const GET_USER_INFO_REQUEST = "GET_USER_INFO_REQUEST";
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const GET_USER_INFO_FAILED = "GET_USER_INFO_FAILED";

//registre
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

//posts
export const ADD_NEW_POST_REQUEST = "ADD_NEW_POST_REQUEST";
export const ADD_NEW_POST_SUCCESS = "ADD_NEW_POST_SUCCESS";
export const ADD_NEW_POST_FAILED = "ADD_NEW_POST_FAILED";

export const GET_POST_REQUEST = "GET_POST_REQUEST ";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_FAILED = "GET_POST_FAILED ";

export const GET_MY_POSTS_REQUEST = "GET_MY_POSTS_REQUEST ";
export const GET_MY_POSTS_SUCCESS = "GET_MY_POSTS_SUCCESS";
export const GET_MY_POSTS_FAILED = "GET_MY_POSS_FAILED ";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST ";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILED = "DELETE_POST_FAILED ";

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST ";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAILED = "UPDATE_POST_FAILED ";

//bookings
export const ADD_NEW_BOOKING_REQUEST = "ADD_NEW_BOOKING_REQUEST";
export const ADD_NEW_BOOKING_SUCCESS = "ADD_NEW_BOOKING_SUCCESS";
export const ADD_NEW_BOOKING_FAILED = "ADD_NEW_BOOKING_FAILED";

export const GET_BOOKINGS_REQUEST = "GET_BOOKINGS_REQUEST";
export const GET_BOOKINGS_SUCCESS = "GET_BOOKINGS_SUCCESS";
export const GET_BOOKINGS_FAILED = "GET_BOOKINGS_FAILED";

export const DELETE_BOOKINGS_REQUEST = "DELETE_BOOKINGS_REQUEST";
export const DELETE_BOOKINGS_SUCCESS = "DELETE_BOOKINGS_SUCCESS";
export const DELETE_BOOKINGS_FAILED = "DELETE_BOOKINGS_FAILED";

export const UPDATE_BOOKINGS_REQUEST = "UPDATE_BOOKINGS_REQUEST";
export const UPDATE_BOOKINGS_SUCCESS = "UPDATE_BOOKINGS_SUCCESS";
export const UPDATE_BOOKINGS_FAILED = "UPDATE_BOOKINGS_FAILED";

//messages
export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILED = "SEND_MESSAGE_FAILED";

export const GET_MESSAGE_REQUEST = "GET_MESSAGE_REQUEST";
export const GET_MESSAGE_SUCCESS = "GET_MESSAGE_SUCCESS";
export const GET_MESSAGE_FAILED = "GET_MESSAGE_FAILED";

export const DELETE_MESSAGE_REQUEST = "DELETE_MESSAGE_REQUEST";
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS";
export const DELETE_MESSAGE_FAILED = "DELETE_MESSAGE_FAILED";

//Subscribe
export const ADD_SUBSCRIPTION_REQUEST = "ADD_SUBSCRIPTION_REQUEST";
export const ADD_SUBSCRIPTION_SUCCESS = "ADD_SUBSCRIPTION_SUCCESS";
export const ADD_SUBSCRIPTION_FAILED = "ADD_SUBSCRIPTION_FAILED";

export const GET_SUBSCRIPTION_REQUEST = "GET_SUBSCRIPTION_REQUEST";
export const GET_SUBSCRIPTION_SUCCESS = "GET_SUBSCRIPTION_SUCCESS";
export const GET_SUBSCRIPTION_FAILED = "GET_SUBSCRIPTION_FAILED";

export const DELETE_SUBSCRIPTION_REQUEST = "DELETE_SUBSCRIPTION_REQUEST";
export const DELETE_SUBSCRIPTION_SUCCESS = "DELETE_SUBSCRIPTION_SUCCESS";
export const DELETE_SUBSCRIPTION_FAILED = "DELETE_SUBSCRIPTION_FAILED";
